### ISSUE TITLE
Replace the firebase links

### ISSUE THREAD

**Issue by Signior-X** [devzes/pnotes#81]
Find all the links like this in the code 
![image](https://user-images.githubusercontent.com/56730716/135745674-ce365ed3-546c-4a1d-bc0d-a89ee437c539.png)

And replace this with the following links
```js
<script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-database.js"></script>

<script src="js/finit.js"></script>
```

See how changes are made in `laptop.ejs` in https://github.com/devzes/pnotes/commit/79e5755d60fc7e0e9ab3de38dee48df95cba0726

**Comment by Signior-X** [comment]
See how changes are made in `laptop.ejs` in https://github.com/devzes/pnotes/commit/79e5755d60fc7e0e9ab3de38dee48df95cba0726

**Comment by Signior-X** [comment]
You need to make changes to `public/org` file.
See the firebase links.

**Comment by Ritam727** [comment]
I would be working on public/share file
