### ISSUE TITLE
Make the placeholder color a bit lighter.

### ISSUE THREAD

**Issue by Signior-X** [devzes/pnotes#84]
See in this image 
![image](https://user-images.githubusercontent.com/56730716/135746695-50c88036-73ad-4d95-8251-0e7c6c220528.png)

The placeholder of search isn't visibile clearly in the dark theme. Make it a bit light so that it becomes visible.

**Comment by melan96** [comment]
Hello @Signior-X. I can go through this and fix this problem. Can you assign this issue for me?

**Comment by Signior-X** [comment]
Sure go ahead @melan96

**Comment by melan96** [comment]
@Signior-X when execute the firebase serve, following requirement is occured. Do you have any testers/dev enabled authentication method?

`Failed to get Firebase project notesapp-09. Please make sure the project exists and your account has permission to access it`

**Comment by Signior-X** [comment]
Hello @melan96 
I have just updated the project. Now you also don't need Node.js to run the project.

See the new README.md and also update your main branch with this repo.
